### ISSUE TITLE
X4 stimulant is just a better version of backup mag

### ISSUE THREAD

**Issue by Heyimmodding** [TeamMoonstorm/Starstorm2#158]
Pretty self explanatory. X4 in its current state outclasses backup mag in every way and is in the same tier as it. There's two solutions to this: either make it a green (which kinda just makes it sunrise smoothie lol) or change the effect/simplify the effect. However adding cdr to your m2 is always going to be better than backup mag.

On an unrelated note, the item doesn't check that the m2 has a cool down, so for example if I use pathfiner and spam r->m2 I get infinite healing

**Comment by Heyimmodding** [comment]
An addendum: by the way, dunno if it stacks 10% cdr but the description makes it seem that way. That's actually insane if so. I think swuff said it's supposed to be flat anyway? I dunno

**Comment by Zenithrium** [comment]
I’ll probably make a one time cd increase? feels a little weird to do that on a white item

**Comment by TeamMoonstorm** [comment]
It feels weird because most whites generally just have one effect that stacks linearly - though X4 definitely doesn't need cdr scaling imo, it shouldn't seek to flat out replace Back-Up Mag.

**Comment by Zenithrium** [comment]
yeah it does have two distinct effects. I like the bit of cdr but it stacking will probably make it too good

**Comment by Heyimmodding** [comment]
The issue with m2 cdr on a white is it will always be better than backup mag which gives none

**Comment by Heyimmodding** [comment]
If it's going to have multiple effects it should probably be a green imo, since in current state it's a bit too good and a bit too complicated for a green item

**Comment by gaforb** [comment]
Just as a counterpoint - M2s that fire immediately like phase round can benefit more from stacking mags over cdr because you can fire all the stored charges at once to chunk a boss to death - similarly, at least one backup mag is often important on charged M2s so they can be restocking while in use (arti nano-bomb for example)

Having both available at white is reasonable since besides command or finding a printer, you arent guaranteed to be able to stack either.

As internal balancing though, i'd suggest you add a hard cap of 70% cdr (approached hyperbolically, similar to tougher times) and prevent the heal from being triggered infinitely (currently only the case for certain modded characters and railgunner's alt m2 i think)

**Comment by TeamMoonstorm** [comment]
I definitely agree with Gaforb here - CDR or not, Back-Up Mag definitely has many specific use cases that make it preferable to X4. 

I still do feel as if it stacking two stats is weird. As a White item, it already doing two things come off as odd design, though I'd personally say the two effects are closely related enough that both could be kept - I'd personally prefer if just one were to stack, for having two different stacking effects for a White feels a bit much?

With that in mind, I'd personally advocate for either:

 · Reduce secondary cooldown by 15%. Using secondary heals you for 5%. Recharges every 5 (-25%, hyperbolic) seconds.

 · Reduce secondary cooldown by 15% (+15%, hyperbolic). Using secondary heals you for 5%. Recharges every 5 seconds.

I'd personally advocate for the former, as it helps move the item into a bit of a different niche from Back-Up Mag - the item still buffs your secondary, but it's focused on healing rather than CDR. A cooldown (a la Kjaro & Runald bands) also helps circumvent nasty hard-coded interactions for countless modded characters, 0 cooldown secondaries, and Back-Up Magazines, while still remaining simple to understand for the player. Keep in mind specific numbers are just spitballs and should possibly be tweaked higher / lower - but that's hard to say without testing it out.

**Comment by gaforb** [comment]
I'm not a fan of item-specific cooldowns personally - and certainly at white it's more unusual. I think the stacking CDR is the majority of the items identity as well. Since the additional effect on top of CDR is new to SS2's version of X4, what about if it granted a regen or armor buff instead of a flat heal? A non-stacking buff would also get around the infinite secondary use issue.

Something like "Reduces secondary skill cooldown by 10% (+10% per stack). Using your secondary skill increases base health regeneration by +2hp/s (+1hp/s per stack) for 2 seconds."

Maybe still a little complex for a white though.

**Comment by swuff-star** [comment]
I don't think white item cooldowns are _too_ alien, though can understand why you'd want to move away from them. Oddly Shaped Opal and (technically?) Safer Spaces are two cooldown dependant whites that come to mind, though I feel as if they handle it fairly differently due to how they're activated and refresh.

Either way - I do think I like your suggestion of a timed buff more than flat healing, and having it be non-stackable sorts out the problem with M2 spam as well. I still think a cooldown is the better solution for _specifically_ tackling the spam issue, though a timed buff will likely feel more natural and fitting both in terms of design as a white item and digestibility as a player (right now the way the item works is a decent bit to wrap your head around - your fix is simple), while still helping address the issue. Good call on that. 👍

...though maybe still too complex, yeah. Its identity in 1 is on the CDR side, and I think if only one effect were to stack (and still believe this should be the case), it should be the CDR.

**Comment by prodzpod** [comment]
why doesnt backup mag give m2 cdr :zanysoup:
