### ISSUE TITLE
Nkota's Heritage procs on re-leveling up from Baby's Toys

### ISSUE THREAD

**Issue by TanmanG** [TeamMoonstorm/Starstorm2#166]
Leveling back the lost levels from Baby's Toys triggers Nkota's Heritage, allowing infinite item generation when using Artifact of Command.

Unsure if this is intended behavior, as it rapidly begins slowing the game from item clutter. Encountered this in 3-player game, all three players were able to replicate the behavior, spawning in dozens of items by taking Baby's Toys with Nkota's Heritage, leveling back up three times rapidly from killing nearby enemies, then re-selecting Baby's Toys from the granted Red command essence.

**Comment by swuff-star** [comment]
This is technically intended behavior I believe? You're saying another item spawns after leveling up, and not when _leveling down_, correct?

I think the issue here is moreso that these items are very exploitable next to each other in Command which admittedly is not much of a balancing concern for myself.

I'll leave this open in case Zen or someone else sees it differently and wants to implement some sort of workaround or fix to prevent this exploit, but given it's a matter of intended interactions coming out very powerful under Artifacts... It sounds like intended behavior™ is all.

**Comment by Zenithrium** [comment]
so it's like....kind of intended if it's re-leveling back up. it's kinda dumb but like thats the consequences of how the items would mechanically interact, and i guess i could nerf / fix it, but i don't really want to unless it seems to be a consensus that this interaction should be adjusted
