### ISSUE TITLE
Backup Magazine completely Breaks Executioner's right click skill

### ISSUE THREAD

**Issue by RocketJay8** [TeamMoonstorm/Starstorm2#190]
Picking up Backup Magazine makes his right click skill break. When it fully recharges, it charges it individually by 1 rather than refilling it by 8, which makes this skill take forever to fully charge.

**Comment by RocketJay8** [comment]
This might also affect Nemesis commando's 8 bullet ability as well.

**Comment by Slipskip** [comment]
I don't think there's ever been a time where Exes M2 recharged fully outside of killing boss enemies. It's always charged one stock at a time after the original balance pass to make it actually usable in fights like Mithrix since it used to just not charge at all.

I'd argue if you ever did experience it recharging every single stock at once that would be [1] absurdly broken given it's the strength of a special on a M2 and [2] that'd legit be a bug since that's not intended.

**Comment by RocketJay8** [comment]
No, I meant completely useless since I can only fire one bullet instead of eight whenever it fully recharges once.

**Comment by Slipskip** [comment]
That justifies a log then since I've just given myself a backup mag and Exe still fires 5 stocks of M2 at a time with or without. Nemmando never unloaded all charges at once if you're referring to Single Tap since it's **Single** tap

**Comment by Zenithrium** [comment]
okay i think this is about nemmando? nemmando only reloads 8 bullets per cooldown of single tap, i can't seem to get it to break to one

**Comment by prodzpod** [comment]
executioner will be reworked in the foreseeable future, please report again if the problem persists
