### ISSUE TITLE
Greater Warbanner + Gesture of the Drowned = Infinite banner spam that kills game on a new stage 

### ISSUE THREAD

**Issue by RetroNutcase** [TeamMoonstorm/Starstorm2#201]
Conditions to reproduce: Buy Gesture of the Drowned while in the Bazaar and having the Greater Warbanner equipped and begin a new stage. May or may not also involve having a fuel cell (I did when this happened).

I spawned them so fast the game basically froze after a couple seconds when I began a new stage.

**Comment by gamrtiem** [comment]
happened to me too, i was talking about it a bit in discussion because i didnt know if it was a bug that is just because of ss2 or a mod conflict. heres a clip of it happening https://files.catbox.moe/9evw6d.mp4 also it seems to only be client side, i was playing with naso and he didnt see any of the banners

**Comment by Zenithrium** [comment]
huh
maybe it's lacking a networkserver check? ill try look into it

**Comment by prodzpod** [comment]
i think someone is looking into this rn, will probably be fixed in april release
