### ISSUE TITLE
Molten coin spamming console every proc, KeyNotFoundException

### ISSUE THREAD

**Issue by gregest** [TeamMoonstorm/Starstorm2#216]
This is two separate errors but both are related to Starstorm so I thought I would put it in 1 report instead of making two separate     

For molten coin, every time it procs it prints "Giving 0 Money" in the console, which becomes very frequent the further you go. Not sure what else I can say about this, it doesn't happen without molten coin.    

The second one, I could not figure out when it happens but it would spam KeyNotFoundException with a very long stacktrace that first mentions Starstorm2, and then a few other mods

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/10670204/LogOutput.log)

**Comment by gaforb** [comment]
The "Giving 0 Money" spam was caused by LIT's Life Savings until the most recent update I think - it would trigger on any Body being spawned. Try updating to the latest version of LIT and see if you still get spam.

As for the KeyNotFound error, that looks to be OnInventoryChanged - I suspect it's a conflict between TILER2's FakeInventory system that it uses for mimics and something else hooking the same function. It mentions several mods that all check the OnInventoryChanged function, including StarStorm2. Try disabling TILER2 and anything depending on it and see if the error still occurs.

**Comment by gregest** [comment]
I was sure that it was molten coin because I was watching the console until I procced it and it showed up as I procced it, I will try to disable tiler2, I did hear that it somehow breaks with everything

**Comment by Darkmega18** [comment]
I saw some molten coin sound related spam myself, so I'm wondering if this is related?

stuff like this:
[Warning:Moonstorm Shared Utils] Could not find sound event with name of MoltenCoin

**Comment by prodzpod** [comment]
love how this is 3 different issue that we cant really do anything with

**Comment by Darkmega18** [comment]
oofs. ._.'

**Comment by prodzpod** [comment]
> The "Giving 0 Money" spam was caused by LIT's Life Savings until the most recent update I think - it would trigger on any Body being spawned. Try updating to the latest version of LIT and see if you still get spam.
> 
> As for the KeyNotFound error, that looks to be OnInventoryChanged - I suspect it's a conflict between TILER2's FakeInventory system that it uses for mimics and something else hooking the same function. It mentions several mods that all check the OnInventoryChanged function, including StarStorm2. Try disabling TILER2 and anything depending on it and see if the error still occurs.

have you tried these and does the issue persist

**Comment by Darkmega18** [comment]
If I disable Tiler won't the mods requiring it start breaking? or do only specific portions of those mods require Tiler like the afformentioned mimic I actually have turned off?

I have the latest of LIT thats available on the launcher fairly certain. I always updated whenever I do. but I've since turned off their life savings for the classic items one for the gold over time rather than consumable gold burst at start of level.

I'll have to see exactly what my molten coin related spam is first to be sure on which fix I might need to try if it's even either.

**Comment by prodzpod** [comment]
TILER2 just updated actually, try the new version and see if the issue persists

**Comment by prodzpod** [comment]
epic thinkinvis win

**Comment by Darkmega18** [comment]
I guess so. didn't see anything related to molten coin when I typed molten into the filter. so, must be good now.
