### ISSUE TITLE
lag bug with Greater warbanner

### ISSUE THREAD

**Issue by s1amdunx** [TeamMoonstorm/Starstorm2#230]
I was doing fine in the void fields with 3 gestures of the drowned and a greater warbanner but when I left it caused them to spawn every frame I think it had something to do with the portable reactor I had gotten at the end but haven't tested it yet. here is a youtube video showing the problem visually
https://youtu.be/1Ld4PIeMDi0

**Comment by bbenyovszky** [comment]
It's not portable reactor I think. It's Warbanner itself.
I did the mistake to give it to an equpment drone. At first it worked just fine. A few (maybe just 1?) levels later it started spamming Greater Warbanner whenever it got near me. No "Maximum 5" limit.

The problem is not only that it absolutely kills the framerate, but also that the row of banners create solid walls. Almost trapped in one of the levels. I tried to kill the drone by luring it into a Greatparent's sun, but it killed every drone of mine BUT that... Lucky bastard.

![Risk of Rain 2 Screenshot 2023 03 28 - 23 30 35 49](https://user-images.githubusercontent.com/29160269/228377280-3b046e7a-cec3-445b-977d-0287ffe75ed2.png)

**Comment by bbenyovszky** [comment]
![Risk of Rain 2 Screenshot 2023 03 29 - 00 12 24 42](https://user-images.githubusercontent.com/29160269/228378316-60b6aaff-de7a-4d8b-ac29-b22578b0c96f.png)
Greater Warbanhell :D

**Comment by SomeoneInParticular** [comment]
I had it as well; occurred when I gave it to an equipment drone. Throughout the run, it seemed to happen most when I stood still though (usually to scrap something, leading to my retinas being burned out)
![RoR_Starstorm_Bug1](https://user-images.githubusercontent.com/43527660/229021781-e93c737d-d9e4-474e-8fab-0cbe07856f09.png)
![RoR_Starstorm_Bug2](https://user-images.githubusercontent.com/43527660/229021787-489ca974-92ea-4b77-9360-e22038e1dc0f.png)

**Comment by prodzpod** [comment]
#201
