### ISSUE TITLE
Chirr's Ancient Scepter ability doesn't carry variant types when moving to the next stage

### ISSUE THREAD

**Issue by Mick0604** [TeamMoonstorm/Starstorm2#431]
after taming a variant monster and proceeding to the next stage as chirr with the ancient scepter the monster loses all variant types and becomes a regular monster. The monster still keeps its elite aspects but just loses the variant.

I am using the Nebby's wrath variants and the original 30 variants.

might just be a mod compatibility thing.

**Comment by Nebby1999** [comment]
I'd have to check how the tamed monster survives between stages. @nayDPz is the master placed in dont destroy on load? or does it have a custom way of saving the monster's metadata?

**Comment by Mick0604** [comment]
Also please let me know if there's any more information I can provide to help.

**Comment by Nebby1999** [comment]
Orbeez just informed me that it sets the character master of the friend to dont destroy on load, however, VAPI cant support VariantDefs being tied to masters at the moment, so i'm closing this issue as "not planned", since its something that should happen in VAPI first before we even consider doing some form of cross-compat between SS2 and VAPI
