### ISSUE TITLE
mastery skin bug?

### ISSUE THREAD

**Issue by acridmain** [TeamMoonstorm/Starstorm2#471]
all of the mastery skins from the vanilla characters dont show up in the character select. they are all still in the logbook as acheivements.

**Comment by swuff-star** [comment]
please post a log of this happening?

r2modman > settings > debugging > 'copy output log'

**Comment by GoddessOfMayo** [comment]
I am having this issue as well since the devotion update. here is my log.  
https://pastebin.com/5ha3Lnts

**Comment by Slipskip** [comment]
Seems like it's based on the the Duplicate fixplugins issue thats been catching people since the update came out as it's also killing all of ss2s events as well.
On the mod manager go to: Settings > profile > export as code > copy code
Profile select > import > from code > paste.

Should solve that issue and pretty much everyone else that has this problem.

**Comment by GoddessOfMayo** [comment]
that did fix it, thanks
