### ISSUE TITLE
Second Player Frozen in Spectate Mode After Warping to Next Stage

### ISSUE THREAD

**Issue by JediEwok1** [TeamMoonstorm/Starstorm2#62]
From what I can tell it's completely random, and we were playing with a ton of other mods so it could be an issue with that.
I know it's not the other mods because I played with someone else with the same mods minus Starstorm 2 so that isn't it.
It could also be an issue with nemmando, that's who he was playing.
But basically what happened was occasionally, especially late in the run, he would get softlocked and stuck in spectate, and then (if we got lucky) it would fix in the next stage. He was still alive on my side and enemies would spawn and agro but he couldn't take any damage.

**Comment by leMalfaisant** [comment]
log of both you and the friend?

**Comment by JediEwok1** [comment]
sorry what do mean by log?

**Comment by swuff-star** [comment]
As you play the game, a "log" is kept of the game's console where any errors are documented (as well as other technical readout information). It can be found by opening r2modmanager, and navigating to the "Debugging" tab of settings (iirc). You should be given an option to "Copy Log Output to Clipboard", and I believe a cache of previous logs is stored as well. 

Since it's been a few days, I'm guessing a log of this issue might not be readily available - ideally send a log after a session in which you and your friend have replicated this issue.

**Comment by JediEwok1** [comment]
ok thanks, when it happens again I'll send it.

**Comment by JediEwok1** [comment]
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/9483298/zipped_log.zip)

**Comment by JediEwok1** [comment]
I tried to exit for proper save and I crashed, just FYI, not the main issue

**Comment by JediEwok1** [comment]
He froze on the last 3 stages

**Comment by JediEwok1** [comment]
[zipped_log.zip](https://github.com/TeamMoonstorm/Starstorm2/files/9483301/zipped_log.zip)
friends log

**Comment by JediEwok1** [comment]
So now it’s happening with other mods too, but I still have no clue what the issue is. I tried uninstalling the one’s I thought were the issue but nothing has worked.

**Comment by Phreelosu** [comment]
it could genuinely be related to PC specs, what amount of memory does your friend have? 8? 16?
according to your description, it is something one of my former classmates experienced for a long time, freezing upon stage transition/never loading into the new stage etc
and it was actually because of reaching the cap of 8 gigs of ram

although if your friend has 16 then maybe the paging file is configured in a way it wont let them use more than x amount of ram otherwise a game just refuses to work.
AND if its not the paging file either then I have no idea either, you might be able to get a little more help in the official modding discord's #tech-support channel

**Comment by JediEwok1** [comment]
I don't think it's a ram issue just because it forces spectate mode, we both have 16, I'll check the paging file, thanks for the help!
