### ISSUE TITLE
Typhoon Unlocks dont have description

### ISSUE THREAD

**Issue by smalllbuddy** [TeamMoonstorm/Starstorm2#623]
Skins unlocked from beating on typhoon have "???" as description.

![image](https://github.com/user-attachments/assets/1b335000-2747-4505-9388-4eeb1b872a04)

**Comment by smalllbuddy** [comment]
Edit: this also applies to monsoon skin unlock for paladin

**Comment by smalllbuddy** [comment]
Edit: Every description in the entire mod is plagued by this issue

**Comment by gamrtiem** [comment]
weird ,., doesnt happen on my game iwth only ss2 
![image](https://github.com/user-attachments/assets/ac9d3917-b10c-4df4-9968-4ac1e3ee2208)
maybe a weird config or mod incompat issue ? log and profile code would be helpful !!

**Comment by Slipskip** [comment]
Potentially solvable with a profile reimport as others have had the ? ? ? stuff since the seekers port and it turns out older config/lang files were messing with it.

On the mod manager go to settings > profile > export as code > copy code then on the profile select screen > import > new > from code > paste.

With any luck it is just older stuff from the profile maybe having been used for prior versions of the mod.

**Comment by smalllbuddy** [comment]
> Potentially solvable with a profile reimport as others have had the ? ? ? stuff since the seekers port and it turns out older config/lang files were messing with it.
> 
> On the mod manager go to settings > profile > export as code > copy code then on the profile select screen > import > new > from code > paste.
> 
> With any luck it is just older stuff from the profile maybe having been used for prior versions of the mod.

thank you sm this fixed the issue precisely :)
