### ISSUE TITLE
Mod not loading correctly

### ISSUE THREAD

**Issue by NaN-12343** [TeamMoonstorm/Starstorm2#628]
I've been trying to download starstorm 2 for a few days now and it doesn't seem to load up correctly, no new survivors, no items nothing. Even with a new profile, where I just download the mod and it's dependencies it doesn't work.
![starstorm2](https://github.com/user-attachments/assets/63eb10fc-5b76-4b2b-a084-a28554620152)
Here is the output log:
[LogOutput.log](https://github.com/user-attachments/files/17535618/LogOutput.log)

**Comment by Hevia** [comment]
Here is a comment we have in the known-issues channel

> Having issues with SS2 not loading? Here is some stuff you can try to fix it (in any order):

> 1. Uninstall SS2, go to profile settings, disable/delete download cache, redownload SS2 (this happens bc SS2 is a large mod and sometimes the download just corrupts)
> 2. Start a new mod profile and download/install your mods there. If you had a lot of mods then slowly add them back
> 3. If playing in another language and SS2 does not load, use english for now until it is fixed
> 4. Try using thunderstore mod manager instead of r2modman (this fixed loading issues for some people) (or try r2modman instead of thunderstore)
> 5. Dont play with deprecated mods

Sadly it looks like the issue with your internet and downloading the mod itself. Likely a corrupted download. Your log doesnt even show starstorm 2 as downloaded so im 99% sure this is the case

Closing the issue because theres nothing we can do to fix this. Its an issue with thunderstore's download speeds + local internet issues causing some sort of corruption of files and it doesnt error to warn or let you know (but the broken logo is a dead giveaway)
